### ISSUE TITLE
Create a new issue raising template

### ISSUE THREAD

**Issue by chinmoy12c** [Samagra-Development/odk-collect-extension#20]
Currently, the issue template used is the original ODK collect app template. We need to customize the template according to our needs.

**Comment by AnjumanHasan** [comment]
Hello @chinmoy12c , I would like to work on this. Could you please assign this to me!

**Comment by chinmoy12c** [comment]
> Hello @chinmoy12c , I would like to work on this. Could you please assign this to me!

sure
