### ISSUE TITLE
Move openForm() and prefillAndOpenForm() methods to FormInteractor

### ISSUE THREAD

**Issue by chinmoy12c** [Samagra-Development/odk-collect-extension#35]
`OdkInteractor` interface should only contain `setupODK` and `resetODK` methods as this interface should only be concerned with High level ODK processes while `openForm`, `openSavedForm` and `prefillAndOpenForm` are specific form level processes and should be moved to `FormsInteractor` interface which is responsible for handling form level processes. The prefill function depends on `updateForm` function which also needs to be moved from `ODKInteractor`.

**Comment by shivenducs1136** [comment]
I would like to work on this issue. 
- I will move the mentioned functions to FormsInteractor as they are form level processes @chinmoy12c

**Comment by Poonam1607** [comment]
Is this issue assigned? If not then I would like to work on this.

**Comment by charanpreet-s** [comment]
Hey @shivenducs1136, Have you started/completed this issue?

@Poonam1607 Let's wait for @shivenducs1136 reply before re-assiging.

**Comment by shivenducs1136** [comment]
Hello, @charanpreet-samagra Yes, I have already begun working on it. 

@Poonam1607 You may play around with other issues, I'll keep you informed on this one.
